name: .NET Core Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    tags:
      - 'v*'
jobs:
  build-and-publish-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore ContributorLicenseAgreement.sln
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Build
      run: dotnet build ContributorLicenseAgreement.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ContributorLicenseAgreement.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings.xml --results-directory ./coverlet-results

    - name: Generate coverage badge
      if: github.ref == 'refs/heads/main'
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
      with:
        reports: './coverlet-results/*/*.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'Badges' # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary

    - name: Update badge in README
      if: github.ref == 'refs/heads/main'
      run: |
        git checkout coverage || git checkout -b coverage
        mkdir -p docs/images
        cp coveragereport/badge_shieldsio_linecoverage_green.svg docs/images/linecoverage.svg
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/images/linecoverage.svg
        git commit -m 'Auto update coverage badge' || exit 0
        git push origin HEAD:coverage
        
    - name: Count Lines of Code (cloc)
      if: github.ref != 'refs/heads/main'
      uses: djdefi/cloc-action@main
    - name: Update cloc file
      if: github.ref != 'refs/heads/main'
      run: |
        git checkout cloc || git checkout -b cloc
        mkdir -p docs/cloc
        cp cloc.txt docs/cloc/cloc.txt
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/cloc/cloc.txt
        git commit -m 'Auto update cloc info' || exit 0
        git push origin HEAD:cloc
    
